default/objects/Trigger_Action__mdt/Trigger_Action__mdt.object-meta.xml
<CustomObject>
    <description>Action calls to the TKWW Trigger Architecture (Q4 2020), mapping a particular SObject/Invocation to an Implementing Class</description>
    <label>Trigger Action</label>
    <pluralLabel>Trigger Actions</pluralLabel>
</CustomObject>

default/objects/Trigger_Action__mdt/fields/Execute_Class__c.field-meta.xml
<CustomField>
    <fullName>Execute_Class__c</fullName>
    <description>Apex class implementing executeMethod for this SObject Implementation</description>
    <inlineHelpText>Apex class implementing executeMethod for this SObject Implementation</inlineHelpText>
    <label>Execute Class</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/Trigger_Action__mdt/fields/isActiveForTesting__c.field-meta.xml
<CustomField>
    <fullName>isActiveForTesting__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Determines whether or not to evaluate this Implementation in the Test context</description>
    <inlineHelpText>Determines whether or not to evaluate this Implementation in the Test context</inlineHelpText>
    <label>isActiveForTesting</label>
    <type>Checkbox</type>
</CustomField>

default/objects/Trigger_Settings_Zyrinx__mdt/fields/SynchronousRecordLimit__c.field-meta.xml
<CustomField>
    <fullName>SynchronousRecordLimit__c</fullName>
    <label>SynchronousRecordLimit</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

default/classes/ZyrinxTriggerArchitectureMetadataService.cls
public without sharing class ZyrinxTriggerArchitectureMetadataService {

    @TestVisible
    public static List<Trigger_Action__mdt> actions = new List<Trigger_Action__mdt>();

    @TestVisible
    public static Map<String, Trigger_Settings_Zyrinx__mdt> mapTriggerSettings;

    @TestVisible
    public static List<Trigger_Action__mdt> getTriggerActions(){

        if(actions!=null && actions.size() > 0){
            // You can override the Trigger_Action__mdt(s) stored in the database by passing Trigger_Action__mdt instance(s)
            // to the ZyrinxTriggerArchitectureMetadataService.actions before the Trigger executes
           return actions;
        }
        else{

            Map<String, Trigger_Action__mdt> mapTriggerActions = Trigger_Action__mdt.getAll();

            for(Trigger_Action__mdt thisRouting : mapTriggerActions.values()){
                if(((Test.isRunningTest() && thisRouting.isActiveForTesting__c == true) ||
                    (Test.isRunningTest() == false)) &&
                    thisRouting.Execute_Class__c != null)
                {
                    actions.add(thisRouting);
                }
            }

            /* if(Test.isRunningTest()){

                for(Trigger_Action__mdt thisRouting : mapTriggerActions.values()){
                    if(thisRouting.isActiveForTesting__c == true && thisRouting.Execute_Class__c != null){
                        actions.add(thisRouting);
                    }
                }
            }
            else{
                for(Trigger_Action__mdt thisRouting : mapTriggerActions.values()){
                    if(thisRouting.Execute_Class__c != null){
                        actions.add(thisRouting);
                    }
                }
            } */
        }
        return actions;
    }

    @TestVisible
    public static Integer getSynchronousRecordLimit(){
        
        if(mapTriggerSettings == null){
            mapTriggerSettings = Trigger_Settings_Zyrinx__mdt.getAll();
        }
        
        return (mapTriggerSettings.size() == 0 || 
                mapTriggerSettings.containsKey('Default')==false ||
                mapTriggerSettings.get('Default').SynchronousRecordLimit__c == null) 
                ? 1 
                : (Integer)mapTriggerSettings.get('Default').SynchronousRecordLimit__c;
    }

}